GitHub actions
Visual-Behavior/aloception pull request #205
Opened 2022-07-22 09:26 UTC by Ardorax

New:
- Github action who automatically launch unit test when there is a commit or pull request in master branch.

Question:
- [ ] Which version of the packages should we use ?
- [ ] Should we check more branch ?

2022-07-28 06:53 UTC, thibo73800 requested changes
All tests do not seem to pass. Is it still a WIP or do you need help to find out why tests do not pass ?

2022-07-28 07:25 UTC, Ardorax commented
I will change the version of pytorch to 10.2. If there is still some problem. I will need some help.

2022-07-28 15:36 UTC, thibo73800 commented
@Data-Iab unit test passed and can now be tested automatically (thanks @Ardorax). But, to make it work I had to remove the changes of one of your last pull request (https://github.com/Visual-Behavior/aloception/pull/194/files). 

When using your changes, it seem that aug tensor are not slice properly when using a bool tensor. It was one of the reason unit tests was not passing anymore.

2022-08-02 06:45 UTC, thibo73800 approved these changes

2022-08-02 06:46 UTC, merged