44 panoptic docs
Visual-Behavior/aloception pull request #94
Opened 2021-09-30 12:02 UTC by Johansmm

New documentations:
* Detr_panoptic
* Panoptic callbacks
* LitPanopticDetr

Update documentation of:  
 * Detr modules (detr, detr-r50 , detrfinetune, train, data_modules, ..)
 * Callbacks
 * Metrics
 * Criterion

And fix link by new DataConnectors modules (explained in #89 )

**Important note: Not merge until merge first #89 ** 

Closes #2 and #44

2021-10-06 07:09 UTC, thibo73800 requested changes

2021-10-06 10:58 UTC, Johansmm commented on alodataset/coco_panoptic_dataset.py
> +        Use when the number of model outputs does not match with the number of classes in the dataset, by default 250
@thibo73800 Ok, I will change in #43

2021-10-06 11:36 UTC, Johansmm commented on alonet/callbacks/base_metrics_callback.py
> +class BaseMetricsCallback(pl.Callback):
@thibo73800 maybe `InstanceBasedMetricsCallbacks` ? The idea with this class is use "any" metric that have the "add_sample" behavior: Add samples in each step and used them to summary the results. But I agree with you. `InstanceBasedMetricsCallbacks` is ok?

2021-10-06 11:51 UTC, Johansmm commented
@thibo73800: For this branch, is required merge first #89 to see the docs changes  only

2021-10-06 12:53 UTC, Johansmm commented on alodataset/coco_panoptic_dataset.py
> +            # Fix label_types
Done

2021-10-06 13:13 UTC, Johansmm commented on alonet/metrics/compute_map.py
> +Examples
Done

2021-10-06 13:13 UTC, Johansmm commented on alonet/metrics/compute_pq.py
> +"""Compute Panoptic, Segmentation and Recognition Qualities Metrics.
Done

2021-10-08 07:38 UTC, thibo73800 commented
Thanks for all the documentation, can  you add detr_panoptic to the main readme along with a specific readme in the detr_panoptic folder ? (Following other models example)

2021-10-08 07:38 UTC, thibo73800 requested changes
Thanks for all the documentation, can you add detr_panoptic to the main readme along with a specific readme in the detr_panoptic folder ? (Following other models example)

2021-10-13 11:00 UTC, thibo73800 approved these changes

2021-10-13 11:00 UTC, merged